// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: transcriptor.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WavChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WavChunk) Reset() {
	*x = WavChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transcriptor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WavChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WavChunk) ProtoMessage() {}

func (x *WavChunk) ProtoReflect() protoreflect.Message {
	mi := &file_transcriptor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WavChunk.ProtoReflect.Descriptor instead.
func (*WavChunk) Descriptor() ([]byte, []int) {
	return file_transcriptor_proto_rawDescGZIP(), []int{0}
}

func (x *WavChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WavResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *WavResponse) Reset() {
	*x = WavResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transcriptor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WavResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WavResponse) ProtoMessage() {}

func (x *WavResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transcriptor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WavResponse.ProtoReflect.Descriptor instead.
func (*WavResponse) Descriptor() ([]byte, []int) {
	return file_transcriptor_proto_rawDescGZIP(), []int{1}
}

func (x *WavResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_transcriptor_proto protoreflect.FileDescriptor

var file_transcriptor_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x67, 0x6f, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x22, 0x1e, 0x0a, 0x08, 0x57,
	0x61, 0x76, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x0b, 0x57,
	0x61, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x32, 0x69,
	0x0a, 0x13, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x57,
	0x61, 0x76, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x57, 0x61, 0x76, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x1a, 0x22, 0x2e, 0x67, 0x6f, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x57, 0x61, 0x76, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x6b, 0x67,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transcriptor_proto_rawDescOnce sync.Once
	file_transcriptor_proto_rawDescData = file_transcriptor_proto_rawDesc
)

func file_transcriptor_proto_rawDescGZIP() []byte {
	file_transcriptor_proto_rawDescOnce.Do(func() {
		file_transcriptor_proto_rawDescData = protoimpl.X.CompressGZIP(file_transcriptor_proto_rawDescData)
	})
	return file_transcriptor_proto_rawDescData
}

var file_transcriptor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transcriptor_proto_goTypes = []interface{}{
	(*WavChunk)(nil),    // 0: goMeetingTranscriptor.WavChunk
	(*WavResponse)(nil), // 1: goMeetingTranscriptor.WavResponse
}
var file_transcriptor_proto_depIdxs = []int32{
	0, // 0: goMeetingTranscriptor.TranscriptorService.StreamWav:input_type -> goMeetingTranscriptor.WavChunk
	1, // 1: goMeetingTranscriptor.TranscriptorService.StreamWav:output_type -> goMeetingTranscriptor.WavResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transcriptor_proto_init() }
func file_transcriptor_proto_init() {
	if File_transcriptor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transcriptor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WavChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transcriptor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WavResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transcriptor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transcriptor_proto_goTypes,
		DependencyIndexes: file_transcriptor_proto_depIdxs,
		MessageInfos:      file_transcriptor_proto_msgTypes,
	}.Build()
	File_transcriptor_proto = out.File
	file_transcriptor_proto_rawDesc = nil
	file_transcriptor_proto_goTypes = nil
	file_transcriptor_proto_depIdxs = nil
}
